server:
  port: 8081


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.15.124:1523/mestest.xinya.com
    username: system
    password: 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#
#logging:
#  file:
#    path: log/
#  level:
#    com.xydz.full-performance-report.mapper: debug

