server:
  #服务器端口配置
  port: 8081

spring:
  #oracle连接配置
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.15.124:1523/mestest.xinya.com
    username: system
    password: 1
  #wagger配置s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#
#logging:
#  file:
#    path: /log
#  level:
#    root: DEBUG
#    com:
#      baomidou:
#        mybatisplus: DEBUG
#      xydz:
#        full-performance-report:
#          mapper: DEBUG

